### ISSUE TITLE
The following ASN1Exception object was thrown building Instance of 'ASN1Exception'

### ISSUE THREAD

**Issue by certaintls** [Ephenodrom/Dart-Basic-Utils#10]
When I was decoding this certificate, I ran into the error below:
````
[+6401 ms] I/flutter (17765): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
[        ] I/flutter (17765): The following ASN1Exception object was thrown building:
[        ] I/flutter (17765):   Instance of 'ASN1Exception'
[        ] I/flutter (17765): 
[        ] I/flutter (17765): When the exception was thrown, this was the stack:
[        ] I/flutter (17765): #0      ASN1Parser._doPrimitive (package:asn1lib/asn1parser.dart:109:9)
[        ] I/flutter (17765): #1      ASN1Parser.nextObject (package:asn1lib/asn1parser.dart:51:13)
[        ] I/flutter (17765): #2      ASN1Sequence._decodeSeq (package:asn1lib/asn1sequence.dart:73:27)
[        ] I/flutter (17765): #3      new ASN1Sequence.fromBytes (package:asn1lib/asn1sequence.dart:23:5)
[        ] I/flutter (17765): #4      ASN1Parser._doPrimitive (package:asn1lib/asn1parser.dart:72:29)
[        ] I/flutter (17765): #5      ASN1Parser.nextObject (package:asn1lib/asn1parser.dart:51:13)
[        ] I/flutter (17765): #6      ASN1Sequence._decodeSeq (package:asn1lib/asn1sequence.dart:73:27)
[        ] I/flutter (17765): #7      new ASN1Sequence.fromBytes (package:asn1lib/asn1sequence.dart:23:5)
[        ] I/flutter (17765): #8      ASN1Parser._doPrimitive (package:asn1lib/asn1parser.dart:72:29)
[        ] I/flutter (17765): #9      ASN1Parser.nextObject (package:asn1lib/asn1parser.dart:51:13)
[        ] I/flutter (17765): #10     ASN1Sequence._decodeSeq (package:asn1lib/asn1sequence.dart:73:27)
[        ] I/flutter (17765): #11     new ASN1Sequence.fromBytes (package:asn1lib/asn1sequence.dart:23:5)
[        ] I/flutter (17765): #12     ASN1Parser._doPrimitive (package:asn1lib/asn1parser.dart:72:29)
[        ] I/flutter (17765): #13     ASN1Parser.nextObject (package:asn1lib/asn1parser.dart:51:13)
[        ] I/flutter (17765): #14     X509Utils.x509CertificateFromPem (package:basic_utils/src/X509Utils.dart:260:34)
````

The PEM string is below:
````
-----BEGIN CERTIFICATE-----
MIIEAzCCAuugAwIBAgIQVID5oHPtPwBMyonY43HmSjANBgkqhkiG9w0BAQUFADB1
MQswCQYDVQQGEwJFRTEiMCAGA1UECgwZQVMgU2VydGlmaXRzZWVyaW1pc2tlc2t1
czEoMCYGA1UEAwwfRUUgQ2VydGlmaWNhdGlvbiBDZW50cmUgUm9vdCBDQTEYMBYG
CSqGSIb3DQEJARYJcGtpQHNrLmVlMCIYDzIwMTAxMDMwMTAxMDMwWhgPMjAzMDEy
MTcyMzU5NTlaMHUxCzAJBgNVBAYTAkVFMSIwIAYDVQQKDBlBUyBTZXJ0aWZpdHNl
ZXJpbWlza2Vza3VzMSgwJgYDVQQDDB9FRSBDZXJ0aWZpY2F0aW9uIENlbnRyZSBS
b290IENBMRgwFgYJKoZIhvcNAQkBFglwa2lAc2suZWUwggEiMA0GCSqGSIb3DQEB
AQUAA4IBDwAwggEKAoIBAQDIIMDs4MVLqwd4lfNE7vsLDP90jmG7sWLqI9iroWUy
euuOF0+W2Ap7kaJjbMeMTC55v6kF/GlclY1i+blw7cNRfdCT5mzrMEvhvH2/UpvO
bntl8jixwKIy72KyaOBhU8E2lf/slLo2rpwcpzIP5Xy0xm90/XsY6KxX7QYgSzIw
WFv9zajmofxwvI6Sc9uXp3whrj3B9UiHbCe9nyV0gVWw93X2PaRka9ZP585ArQ/d
MtO8ihJTmMmJ+xAdTX7Nfh9WDSFwhfYggx/2uh8Ej+p3iDXE/+pOoYtNP2MbRMNE
1CV2yreN1x5KZmTNXMWcg+HCCIia7E6j8T4cLNlsHaFLAgMBAAGjgYowgYcwDwYD
VR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFBLyWj7qVhy/
zQas8fElyalL1BSZMEUGA1UdJQQ+MDwGCCsGAQUFBwMCBggrBgEFBQcDAQYIKwYB
BQUHAwMGCCsGAQUFBwMEBggrBgEFBQcDCAYIKwYBBQUHAwkwDQYJKoZIhvcNAQEF
BQADggEBAHv25MANqhlHt01Xo/6tu7Fq1Q+e2+RjxY6hUFaTlrg4wCQiZrxTFGGV
v9DHKpY5P30osxBAIWrEr7BSdxjhlthWXePdNl4dp1BUoMUq5KqMlIpPnTX/dqQG
E5Gion0ARD9V04I8GtVbvFZMIi5GQ4okQC3zErg7cBqklrkar4dBGmoYDQZPxz5u
uSlNDUmJEYcyW+ZLBMjkXOZ0c5RdFpgTlf7727FE5TpwrDdr5rMzcijJs1eg9gIW
iAYLtqZLICjU3j2LrTcFU3T+bsy8QxdxXvnFzBqpYe73dgzzcvRyrc9yAjYHR8/v
GVCJYMzpJJUPwssd8m92kMfMdcGWxZ0=
-----END CERTIFICATE-----
````
The data in text format is:
````
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            54:80:f9:a0:73:ed:3f:00:4c:ca:89:d8:e3:71:e6:4a
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: C=EE, O=AS Sertifitseerimiskeskus, CN=EE Certification Centre Root CA/emailAddress=pki@sk.ee
        Validity
            Not Before: Oct 30 10:10:30 2010 GMT
            Not After : Dec 17 23:59:59 2030 GMT
        Subject: C=EE, O=AS Sertifitseerimiskeskus, CN=EE Certification Centre Root CA/emailAddress=pki@sk.ee
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:c8:20:c0:ec:e0:c5:4b:ab:07:78:95:f3:44:ee:
                    fb:0b:0c:ff:74:8e:61:bb:b1:62:ea:23:d8:ab:a1:
                    65:32:7a:eb:8e:17:4f:96:d8:0a:7b:91:a2:63:6c:
                    c7:8c:4c:2e:79:bf:a9:05:fc:69:5c:95:8d:62:f9:
                    b9:70:ed:c3:51:7d:d0:93:e6:6c:eb:30:4b:e1:bc:
                    7d:bf:52:9b:ce:6e:7b:65:f2:38:b1:c0:a2:32:ef:
                    62:b2:68:e0:61:53:c1:36:95:ff:ec:94:ba:36:ae:
                    9c:1c:a7:32:0f:e5:7c:b4:c6:6f:74:fd:7b:18:e8:
                    ac:57:ed:06:20:4b:32:30:58:5b:fd:cd:a8:e6:a1:
                    fc:70:bc:8e:92:73:db:97:a7:7c:21:ae:3d:c1:f5:
                    48:87:6c:27:bd:9f:25:74:81:55:b0:f7:75:f6:3d:
                    a4:64:6b:d6:4f:e7:ce:40:ad:0f:dd:32:d3:bc:8a:
                    12:53:98:c9:89:fb:10:1d:4d:7e:cd:7e:1f:56:0d:
                    21:70:85:f6:20:83:1f:f6:ba:1f:04:8f:ea:77:88:
                    35:c4:ff:ea:4e:a1:8b:4d:3f:63:1b:44:c3:44:d4:
                    25:76:ca:b7:8d:d7:1e:4a:66:64:cd:5c:c5:9c:83:
                    e1:c2:08:88:9a:ec:4e:a3:f1:3e:1c:2c:d9:6c:1d:
                    a1:4b
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Subject Key Identifier: 
                12:F2:5A:3E:EA:56:1C:BF:CD:06:AC:F1:F1:25:C9:A9:4B:D4:14:99
            X509v3 Extended Key Usage: 
                TLS Web Client Authentication, TLS Web Server Authentication, Code Signing, E-mail Protection, Time Stamping, OCSP Signing
    Signature Algorithm: sha1WithRSAEncryption
         7b:f6:e4:c0:0d:aa:19:47:b7:4d:57:a3:fe:ad:bb:b1:6a:d5:
         0f:9e:db:e4:63:c5:8e:a1:50:56:93:96:b8:38:c0:24:22:66:
         bc:53:14:61:95:bf:d0:c7:2a:96:39:3f:7d:28:b3:10:40:21:
         6a:c4:af:b0:52:77:18:e1:96:d8:56:5d:e3:dd:36:5e:1d:a7:
         50:54:a0:c5:2a:e4:aa:8c:94:8a:4f:9d:35:ff:76:a4:06:13:
         91:a2:a2:7d:00:44:3f:55:d3:82:3c:1a:d5:5b:bc:56:4c:22:
         2e:46:43:8a:24:40:2d:f3:12:b8:3b:70:1a:a4:96:b9:1a:af:
         87:41:1a:6a:18:0d:06:4f:c7:3e:6e:b9:29:4d:0d:49:89:11:
         87:32:5b:e6:4b:04:c8:e4:5c:e6:74:73:94:5d:16:98:13:95:
         fe:fb:db:b1:44:e5:3a:70:ac:37:6b:e6:b3:33:72:28:c9:b3:
         57:a0:f6:02:16:88:06:0b:b6:a6:4b:20:28:d4:de:3d:8b:ad:
         37:05:53:74:fe:6e:cc:bc:43:17:71:5e:f9:c5:cc:1a:a9:61:
         ee:f7:76:0c:f3:72:f4:72:ad:cf:72:02:36:07:47:cf:ef:19:
         50:89:60:cc:e9:24:95:0f:c2:cb:1d:f2:6f:76:90:c7:cc:75:
         c1:96:c5:9d
SHA1 Fingerprint=C9:A8:B9:E7:55:80:5E:58:E3:53:77:A7:25:EB:AF:C3:7B:27:CC:D7
```` 
ASN.1 JavaScript decoder of this certificate is at
http://lapo.it/asn1js/#MIIEAzCCAuugAwIBAgIQVID5oHPtPwBMyonY43HmSjANBgkqhkiG9w0BAQUFADB1MQswCQYDVQQGEwJFRTEiMCAGA1UECgwZQVMgU2VydGlmaXRzZWVyaW1pc2tlc2t1czEoMCYGA1UEAwwfRUUgQ2VydGlmaWNhdGlvbiBDZW50cmUgUm9vdCBDQTEYMBYGCSqGSIb3DQEJARYJcGtpQHNrLmVlMCIYDzIwMTAxMDMwMTAxMDMwWhgPMjAzMDEyMTcyMzU5NTlaMHUxCzAJBgNVBAYTAkVFMSIwIAYDVQQKDBlBUyBTZXJ0aWZpdHNlZXJpbWlza2Vza3VzMSgwJgYDVQQDDB9FRSBDZXJ0aWZpY2F0aW9uIENlbnRyZSBSb290IENBMRgwFgYJKoZIhvcNAQkBFglwa2lAc2suZWUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDIIMDs4MVLqwd4lfNE7vsLDP90jmG7sWLqI9iroWUyeuuOF0-W2Ap7kaJjbMeMTC55v6kF_GlclY1i-blw7cNRfdCT5mzrMEvhvH2_UpvObntl8jixwKIy72KyaOBhU8E2lf_slLo2rpwcpzIP5Xy0xm90_XsY6KxX7QYgSzIwWFv9zajmofxwvI6Sc9uXp3whrj3B9UiHbCe9nyV0gVWw93X2PaRka9ZP585ArQ_dMtO8ihJTmMmJ-xAdTX7Nfh9WDSFwhfYggx_2uh8Ej-p3iDXE_-pOoYtNP2MbRMNE1CV2yreN1x5KZmTNXMWcg-HCCIia7E6j8T4cLNlsHaFLAgMBAAGjgYowgYcwDwYDVR0TAQH_BAUwAwEB_zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFBLyWj7qVhy_zQas8fElyalL1BSZMEUGA1UdJQQ-MDwGCCsGAQUFBwMCBggrBgEFBQcDAQYIKwYBBQUHAwMGCCsGAQUFBwMEBggrBgEFBQcDCAYIKwYBBQUHAwkwDQYJKoZIhvcNAQEFBQADggEBAHv25MANqhlHt01Xo_6tu7Fq1Q-e2-RjxY6hUFaTlrg4wCQiZrxTFGGVv9DHKpY5P30osxBAIWrEr7BSdxjhlthWXePdNl4dp1BUoMUq5KqMlIpPnTX_dqQGE5Gion0ARD9V04I8GtVbvFZMIi5GQ4okQC3zErg7cBqklrkar4dBGmoYDQZPxz5uuSlNDUmJEYcyW-ZLBMjkXOZ0c5RdFpgTlf7727FE5TpwrDdr5rMzcijJs1eg9gIWiAYLtqZLICjU3j2LrTcFU3T-bsy8QxdxXvnFzBqpYe73dgzzcvRyrc9yAjYHR8_vGVCJYMzpJJUPwssd8m92kMfMdcGWxZ0

**Comment by Ephenodrom** [comment]
Hello @certaintls 
The problem seems to be the NotAfter and NotBefore date. Normally this seems to be an UTC DateTime, but in this PEM it is a GeneralizedTime. The ASN1 package can't handle this type at the moment, will try to implement this the next days.

Regards

**Comment by Ephenodrom** [comment]
@certaintls 
Please update to version 2.5.0. This should be now fixed.

Regards

**Comment by certaintls** [comment]
2.5.0 fixed the error on the certificate that I reported above, but the similar/same error is still thrown on a different certificate below:

````
#0      ASN1Parser._doPrimitive (package:asn1lib/asn1parser.dart:112:9)
#1      ASN1Parser.nextObject (package:asn1lib/asn1parser.dart:51:13)
#2      ASN1Sequence._decodeSeq (package:asn1lib/asn1sequence.dart:73:27)
#3      new ASN1Sequence.fromBytes (package:asn1lib/asn1sequence.dart:23:5)
#4      ASN1Parser._doPrimitive (package:asn1lib/asn1parser.dart:72:29)
#5      ASN1Parser.nextObject (package:asn1lib/asn1parser.dart:51:13)
#6      ASN1Set._decodeSet (package:asn1lib/asn1set.dart:67:27)
#7      new ASN1Set.fromBytes (package:asn1lib/asn1set.dart:18:5)
#8      ASN1Parser._doPrimitive (package:asn1lib/asn1parser.dart:88:24)
#9      ASN1Parser.nextObject (package:asn1lib/asn1parser.dart:51:13)
#10     ASN1Sequence._decodeSeq (package:asn1lib/asn1sequence.dart:73:27)
#11     new ASN1Sequence.fromBytes (package:asn1lib/asn1sequence.dart:23:5)
#12     ASN1Parser._doPrimitive (package:asn1lib/asn1parser.dart:72:29)
#13     ASN1Parser.nextObject (package:asn1lib/asn1parser.dart:51:13)
#14     ASN1Sequence._decodeSeq (package:asn1lib/asn1sequence.dart:73:27)
#15     new ASN1Sequence.fromBytes (package:asn1lib/asn1sequence.dart:23:5)
#16     ASN1Parser._doPrimitive (package:asn1lib/asn1parser.dart:72:29)
#17     ASN1Parser.nextObject (package:asn1lib/asn1parser.dart:51:13)
#18     ASN1Sequence._decodeSeq (package:asn1lib/asn1sequence.dart:73:27)
#19     new ASN1Sequence.fromBytes (package:asn1lib/asn1sequence.dart:23:5)
#20     ASN1Parser._doPrimitive (package:asn1lib/asn1parser.dart:72:29)
#21     ASN1Parser.nextObject (package:asn1lib/asn1parser.dart:51:13)
#22     X509Utils.x509CertificateFromPem (package:basic_utils/src/X509Utils.dart:260:34)
````

````
-----BEGIN CERTIFICATE-----
MIIEKjCCAxKgAwIBAgIEOGPe+DANBgkqhkiG9w0BAQUFADCBtDEUMBIGA1UEChML
RW50cnVzdC5uZXQxQDA+BgNVBAsUN3d3dy5lbnRydXN0Lm5ldC9DUFNfMjA0OCBp
bmNvcnAuIGJ5IHJlZi4gKGxpbWl0cyBsaWFiLikxJTAjBgNVBAsTHChjKSAxOTk5
IEVudHJ1c3QubmV0IExpbWl0ZWQxMzAxBgNVBAMTKkVudHJ1c3QubmV0IENlcnRp
ZmljYXRpb24gQXV0aG9yaXR5ICgyMDQ4KTAeFw05OTEyMjQxNzUwNTFaFw0yOTA3
MjQxNDE1MTJaMIG0MRQwEgYDVQQKEwtFbnRydXN0Lm5ldDFAMD4GA1UECxQ3d3d3
LmVudHJ1c3QubmV0L0NQU18yMDQ4IGluY29ycC4gYnkgcmVmLiAobGltaXRzIGxp
YWIuKTElMCMGA1UECxMcKGMpIDE5OTkgRW50cnVzdC5uZXQgTGltaXRlZDEzMDEG
A1UEAxMqRW50cnVzdC5uZXQgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkgKDIwNDgp
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArU1LqRKGsuqjIAcVFmQq
K0vRvwtKTY7tgHalZ7d4QMBzQshowNtTK91euHaYNZOLGp18EzoOH1u3Hs/lJBQe
sYGpjX24zGtLA/ECDNyrpUAkAH90lKGdCCmziAv1h3edVc3kw37XamSrhRSGlVuX
MlBvPci6Zgzj/L24ScF2iUkZ/cCovYmjZy/Gn7xxGWC4LeksyZB2ZnuU4q941mVT
XTzWnLLPKQP5L6RQstRIzgUyVYr9smRMDuSYB3Xbf9+5CFVghTAp+XtIpGmG4zU/
HoZdenoVve8AjhUiVBcAkCaTvA5JaJG/+EfTnZVCwQ5N328mz8MYIWJmQ3DW1cAH
4QIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zAdBgNV
HQ4EFgQUVeSB0RGAvtiJuQijMfmhJAkWuXAwDQYJKoZIhvcNAQEFBQADggEBADub
j1abMOdTmXx6eadNl9cZlZD7Bh/KM3xGY4+WZiT6QBshJ8rmcnPyT/4xmf3IDExo
U8aAghOY+rat2l098c5u9hURlIIM7j+VrxGrD9cv3h8Dj1csHsm7mhpElesYT6Yf
zX1XEC+bBAlahLVu2B064dae0Wx5XnkcFMXj0EyTO2U87d89vqbllRrDtRnDvV5b
u/8j72gZyxKTJ1wDLW8w0B62GqzeWvfRqqgnpv55gcR5mTNXuhKwqeBCbJPKVt7+
bYQLCIt+jerXmCHG8+c8eS9enNFMFY3h7CI3zJpDC5fcgJCNs2ebb0gIFVbPv/Er
fF6adulZkMV8gzURZVE=
-----END CERTIFICATE-----
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 946069240 (0x3863def8)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: O=Entrust.net, OU=www.entrust.net/CPS_2048 incorp. by ref. (limits liab.), OU=(c) 1999 Entrust.net Limited, CN=Entrust.net Certification Authority (2048)
        Validity
            Not Before: Dec 24 17:50:51 1999 GMT
            Not After : Jul 24 14:15:12 2029 GMT
        Subject: O=Entrust.net, OU=www.entrust.net/CPS_2048 incorp. by ref. (limits liab.), OU=(c) 1999 Entrust.net Limited, CN=Entrust.net Certification Authority (2048)
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:ad:4d:4b:a9:12:86:b2:ea:a3:20:07:15:16:64:
                    2a:2b:4b:d1:bf:0b:4a:4d:8e:ed:80:76:a5:67:b7:
                    78:40:c0:73:42:c8:68:c0:db:53:2b:dd:5e:b8:76:
                    98:35:93:8b:1a:9d:7c:13:3a:0e:1f:5b:b7:1e:cf:
                    e5:24:14:1e:b1:81:a9:8d:7d:b8:cc:6b:4b:03:f1:
                    02:0c:dc:ab:a5:40:24:00:7f:74:94:a1:9d:08:29:
                    b3:88:0b:f5:87:77:9d:55:cd:e4:c3:7e:d7:6a:64:
                    ab:85:14:86:95:5b:97:32:50:6f:3d:c8:ba:66:0c:
                    e3:fc:bd:b8:49:c1:76:89:49:19:fd:c0:a8:bd:89:
                    a3:67:2f:c6:9f:bc:71:19:60:b8:2d:e9:2c:c9:90:
                    76:66:7b:94:e2:af:78:d6:65:53:5d:3c:d6:9c:b2:
                    cf:29:03:f9:2f:a4:50:b2:d4:48:ce:05:32:55:8a:
                    fd:b2:64:4c:0e:e4:98:07:75:db:7f:df:b9:08:55:
                    60:85:30:29:f9:7b:48:a4:69:86:e3:35:3f:1e:86:
                    5d:7a:7a:15:bd:ef:00:8e:15:22:54:17:00:90:26:
                    93:bc:0e:49:68:91:bf:f8:47:d3:9d:95:42:c1:0e:
                    4d:df:6f:26:cf:c3:18:21:62:66:43:70:d6:d5:c0:
                    07:e1
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Certificate Sign, CRL Sign
            X509v3 Basic Constraints: critical
                CA:TRUE
            X509v3 Subject Key Identifier: 
                55:E4:81:D1:11:80:BE:D8:89:B9:08:A3:31:F9:A1:24:09:16:B9:70
    Signature Algorithm: sha1WithRSAEncryption
         3b:9b:8f:56:9b:30:e7:53:99:7c:7a:79:a7:4d:97:d7:19:95:
         90:fb:06:1f:ca:33:7c:46:63:8f:96:66:24:fa:40:1b:21:27:
         ca:e6:72:73:f2:4f:fe:31:99:fd:c8:0c:4c:68:53:c6:80:82:
         13:98:fa:b6:ad:da:5d:3d:f1:ce:6e:f6:15:11:94:82:0c:ee:
         3f:95:af:11:ab:0f:d7:2f:de:1f:03:8f:57:2c:1e:c9:bb:9a:
         1a:44:95:eb:18:4f:a6:1f:cd:7d:57:10:2f:9b:04:09:5a:84:
         b5:6e:d8:1d:3a:e1:d6:9e:d1:6c:79:5e:79:1c:14:c5:e3:d0:
         4c:93:3b:65:3c:ed:df:3d:be:a6:e5:95:1a:c3:b5:19:c3:bd:
         5e:5b:bb:ff:23:ef:68:19:cb:12:93:27:5c:03:2d:6f:30:d0:
         1e:b6:1a:ac:de:5a:f7:d1:aa:a8:27:a6:fe:79:81:c4:79:99:
         33:57:ba:12:b0:a9:e0:42:6c:93:ca:56:de:fe:6d:84:0b:08:
         8b:7e:8d:ea:d7:98:21:c6:f3:e7:3c:79:2f:5e:9c:d1:4c:15:
         8d:e1:ec:22:37:cc:9a:43:0b:97:dc:80:90:8d:b3:67:9b:6f:
         48:08:15:56:cf:bf:f1:2b:7c:5e:9a:76:e9:59:90:c5:7c:83:
         35:11:65:51
SHA1 Fingerprint=50:30:06:09:1D:97:D4:F5:AE:39:F7:CB:E7:92:7D:7D:65:2D:34:31
````

@Ephenodrom Would you mind taking another look?

**Comment by Ephenodrom** [comment]
@certaintls This PEM contains a TeletextString ( ASN1 Tag 20 ). The ASN1 package can't handle this at the moment. Will implement this, the next days.

**Comment by Ephenodrom** [comment]
@certaintls I updated the asn1lib package and my package. Please update to 2.5.1 and it should be fixed now. 

Please give feedback if it is fixed.

**Comment by certaintls** [comment]
I confirm 2.5.1 fixed the second bug in this issue. Thanks again!
