### ISSUE TITLE
Crypto: Type 'ASN1Sequence' is not a subtype of type 'ASN1Integer'

### ISSUE THREAD

**Issue by larssn** [Ephenodrom/Dart-Basic-Utils#108]
I'm trying to read the following public certificate (pem):
```
-----BEGIN CERTIFICATE-----
MIIGUjCCBIagAwIBAgIUZLBJrCCkrmubG6GrwvsOlMXxYP4wQQYJKoZIhvcNAQEK
MDSgDzANBglghkgBZQMEAgEFAKEcMBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgEF
AKIDAgEgMFYxLTArBgNVBAMMJERlbiBEYW5za2UgU3RhdCBPQ0VTIHVkc3RlZGVu
ZGUtQ0EgMTEYMBYGA1UECgwPRGVuIERhbnNrZSBTdGF0MQswCQYDVQQGEwJESzAe
Fw0yMzEyMDgxMTIzMTlaFw0yNjEyMDcxMTIzMThaMIGJMRMwEQYDVQQDDAp0aWxs
dHkgUE9TMTcwNQYDVQQFEy5VSTpESy1POkc6OGE1ZTcwOWEtNTEyNi00MDg1LTlh
YzAtYTFiZDI4ZTNkYWY5MRMwEQYDVQQKDAp0aWxsdHkgQXBTMRcwFQYDVQRhDA5O
VFJESy0zMjgyNjU2MzELMAkGA1UEBhMCREswggGiMA0GCSqGSIb3DQEBAQUAA4IB
jwAwggGKAoIBgQC81L+HWHvw07hTbUyj9nlmcU6+TGhtXkJQbfvt4NQF7Ay58ipl
s9mYEex8aTUgVOlmrvwZcyrGUPh6ONd11QNJogk93xsJexvRdCLO0p9HfuwolX/a
LGCJNxsSfRWaxBNb6sdVepDzCIbDAa2YPbdM0h9EMXfjREywBByR69s+onbNYPRt
82eYPcTVVfD2hk/JPsAjPN/6VtOzY0TGnHuD6yHod0IdeuIWzMxYiNeD0k5UKZiW
WKRUKGCwePrZFm0HAjLWdMMKMsg2XSkgOtQ3peALXENEtua60y4wA9nFdvGRWGlF
PHKnq7Y6uhVub0kgunqk8ouUHvE6ssBWDjaLmdYVqRg+BJtzsi93T1tIUE6CP9O5
tgk1T0nvj9YDCzirJQVrO8RW6iIdFu1M0kY66pbp3LqojTv2oWW0t9H1/6N8awFO
+0Ga2FtHavFHQRcU7QQBUMwsd3aTCuhec5uoqIqeJfCiKIDWvSgPLsM8ddztL/yI
0+Vw1c2l6FNDHTUCAwEAAaOCAXowggF2MAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgw
FoAUTAHiynO8w744Cjg9NrBcdJx7l7kwcwYIKwYBBQUHAQEEZzBlMD8GCCsGAQUF
BzAChjNodHRwOi8vY2ExLmdvdi5kay9vY2VzL2lzc3VpbmcvMS9jYWNlcnQvaXNz
dWluZy5jZXIwIgYIKwYBBQUHMAGGFmh0dHA6Ly9jYTEuZ292LmRrL29jc3AwIQYD
VR0gBBowGDAIBgYEAI96AQEwDAYKKoFQgSkBAQEDBzA7BggrBgEFBQcBAwQvMC0w
KwYIKwYBBQUHCwIwHwYHBACL7EkBAjAUhhJodHRwczovL3VpZC5nb3YuZGswQQYD
VR0fBDowODA2oDSgMoYwaHR0cDovL2NhMS5nb3YuZGsvb2Nlcy9pc3N1aW5nLzEv
Y3JsL2lzc3VpbmcuY3JsMB0GA1UdDgQWBBSoAXHDecdqw4nuXbVQx05SqFCL+jAO
BgNVHQ8BAf8EBAMCBaAwQQYJKoZIhvcNAQEKMDSgDzANBglghkgBZQMEAgEFAKEc
MBoGCSqGSIb3DQEBCDANBglghkgBZQMEAgEFAKIDAgEgA4IBgQAz+2c+3RVIaosx
BLVsHziJ4wuP+TIwj54CGbJdZBOoiFac886toJjQ/wtpri94y84JnRdMCZZjVEqC
CLruKzPYnzNx3a6aoC4sf4O5kRKUsgEslJozHWUdaraqX6JmSOx6LLCQm6HcV9fV
8D64AzXKRfkscckrm17KPDMtu2eCBHB5dIT1D/hpb7RxPrEyU8pJQNPax32TGxdp
Lq7wALDqHAbOU+tAtXFX8KAcHmddCD6nwXYeKwzU833jmGT+moLNRSjp273TMwwi
UucOaVP3RMk07XWUDzdppW9dILOSmrtVJmH9zU+CbzfY8MjKdEj0kUK2dtoyAq9b
SSzqYxr1QYhDZW3CD4IcojArDenCz+rNw5Ll9yv5jZhylkzq5w69NetjDgXkj60N
LfAWCwR0jHtgsvilJ82FnY/Fqei32UoDCIKFjRRiGwLOmS328jOOPpQmS0X2NLGu
ZgndN5R1s9rwHnd7f9LHVNG6Bicr+YXRzu9PRCxZcWFnRV/psAo=
-----END CERTIFICATE-----
```

It contains a 3072 bit RSA public key.

However when using `CryptoUtils.rsaPublicKeyFromPem(myPem);` it throws an exception:
```
I/flutter ( 8208): ══╡ EXCEPTION CAUGHT BY FLUTTER FRAMEWORK ╞═════════════════════════════════════════════════════════
I/flutter ( 8208): The following _CastError was thrown:
I/flutter ( 8208): type 'ASN1Sequence' is not a subtype of type 'ASN1Integer' in type cast
I/flutter ( 8208):
I/flutter ( 8208): When the exception was thrown, this was the stack:
I/flutter ( 8208): #0      CryptoUtils.rsaPublicKeyFromDERBytes   CryptoUtils.dart:541
I/flutter ( 8208): #1      CryptoUtils.rsaPublicKeyFromPem   CryptoUtils.dart:522
```

**Comment by Ephenodrom** [comment]
@larssn Please try the latest version 5.8.1 on pub.dev. I was able to parse the certificate with that version.
