### ISSUE TITLE
".." crash

### ISSUE THREAD

**Issue by modulovalue** [Ephenodrom/Dart-Basic-Utils#7]
Thank you for the fast fix with the last issue!

Unfortunately, I've found another edge-case

```
The method 'contains' was called on null.
flutter: Receiver: null
flutter: Tried calling: contains("")
```

at 
```
 When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
flutter: #1      DomainUtils.isSubTld (package:basic_utils/src/DomainUtils.dart:30:17)
flutter: #2      DomainUtils.isSubDomain (package:basic_utils/src/DomainUtils.dart:55:17)
flutter: #3      DomainUtils.isDomainName (package:basic_utils/src/DomainUtils.dart:18:31)
```
for the input ".." (just two consecutive dots)

Thanks

**Comment by Ephenodrom** [comment]
@modulovalue 

This is fixed with version 2.3.7. I already published it to pub.dev.

Feel free to check some other methods :).

Regards
