### ISSUE TITLE
UnsupportedASN1TagException: Tag 175 is not supported yet

### ISSUE THREAD

**Issue by reynaldi-lorenzo** [Ephenodrom/Dart-Basic-Utils#91]
Hello.
I want to know, why do i keep getting this error when implementing in active project. But this doesn't occured in fresh flutter project? using same certificate, same coding like this one :

      final bytes = await file.readAsBytes();
      final results = Pkcs12Utils.parsePkcs12(bytes,
        password: password,
      );
      final data = X509Utils.x509CertificateFromPem(results[1]);
      final map = <String, String?>{};

      for (MapEntry<String, String?> entry in data.tbsCertificate!.issuer.entries) {
        map[ASN1ObjectIdentifier.fromIdentifierString(entry.key).readableName ?? '-'] = entry.value;
     }

I/flutter ( 8757): UnsupportedASN1TagException: Tag 175 is not supported yet
I/flutter ( 8757): #0      ASN1Parser._createConstructed (package:pointycastle/asn1/asn1_parser.dart:116:9)
I/flutter ( 8757): #1      ASN1Parser.nextObject (package:pointycastle/asn1/asn1_parser.dart:77:13)
I/flutter ( 8757): #2      new ASN1Sequence.fromBytes (package:pointycastle/asn1/primitives/asn1_sequence.dart:28:28)
I/flutter ( 8757): #3      Pkcs12Utils.parsePkcs12 (package:basic_utils/src/pkcs12_utils.dart:657:32)

**Comment by Ephenodrom** [comment]
Hello and thank you for the issue. The "parse" method is not yet finished and therefore there are still some bugs left. If time permits I will work on it and finish it. Currently it supports only the same algorithms that can be used in the generatePkcs12() method. I assume that the error comes up due to the PKCS12 you tried to parse was encrypted with AES, that is currently not supported.
